theme: jekyll-theme-minimal
title: Soo Hyung Park
description: Currently pursuing Master's Degree in Computer Science. Mainly interested in ML/DL.
author_profile: true
header:
  image: https://i.imgur.com/QHfxvwa.jpg
  image_description: "Mt. Rainier"