theme: jekyll-theme-minimal
title: Soo Hyung Park
logo: https://38.media.tumblr.com/0f77bf82b9c18d9def15be496afa66e7/tumblr_nqfd57nbVO1uum06fo1_400.gif
show_downloads: false
description: "Currently pursuing Master's Degree in Computer Science."
author_profile: true
blog: https://shstan.tistory.com/
header:
  image: https://i.imgur.com/QHfxvwa.jpg
  image_description: "Mt. Rainier"
